name: dart_dyncache
description: an attempt a dynamic and flexible library for all caching needs
version: 1.0.2
homepage: https://github.com/kralverde/dart-dyncache

environment:
  sdk: '>=2.17.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
